site_name: Bookshelf
site_url: https://ivancheban.github.io/bookshelf/
nav:
    - Introduction: 'index.md'
    - Favorites:
        - 'favorites.md'
    - Read:
        - 'read.md'
    - Reading:
        - 'reading.md'
    - Want to read:
        - 'wanna-read.md'
    - About:
        - 'About me': 'about.md'
theme:
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
  name: material
  logo: img/logo.svg
  favicon: img/favicon.ico
  palette: 
    scheme: default
    accent: blue
  
extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ivancheban
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/ivan-cheban-a24b576
  generator: false

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
copyright: Copyright &copy; 2023 Ivan Cheban 


